### ISSUE TITLE
Upgrade Substance GUI library

### ISSUE THREAD

**Issue by Aries85** [ktgw0316/LightZone#11]
Current _Substance_ look and feel library version in LZ project is 3.3. The library is now discontinued and kept under name _[Insubstantial](http://insubstantial.posterous.com/)_ and is in version 7.2.1

The API has changed significantly, LZ needs to be modified.

**Comment by shaleh** [comment]
Status?

**Comment by ktgw0316** [comment]
@yurivict Please use:
```shell
ant -f linux/build.xml -Dno-ivy=true -Dno-submodule=true
```

I added this in `linux/BUILD-Linux.md`.

**Comment by ktgw0316** [comment]
We stopped to use the substance since 5.0.0beta1.  cf. #273.
