### ISSUE TITLE
LIGHTZONE 4.1.0beta11/12 cannot edit PANASONIC GX7 RW2 RAW FILE

### ISSUE THREAD

**Issue by ADAM-SJ** [ktgw0316/LightZone#132]
LIGHTZONE 4.1.0beta11/12 cannot edit PANASONIC GX7 RW2 RAW FILE
1. On preview pane where show thumbnails of files in folder JPG files display. RW2 does not but instead get an image that is like 35mm film with a white egg in the middle.
2. Browse of the RW2 files works and shows the correct image. However when try to get get
   “Unknown error opening this file” “class java lang.NullPointerException”

**Comment by ADAM-SJ** [comment]
Hi there Masahiro
I tried to send the output.pgm file by email but it is too big. I can’t remember how I sent you a RAW file before. Can you remind me?
Thanks for you continuing efforts
Adam

**Comment by ktgw0316** [comment]
Hi Adam,
Would you upload the output.pgm into my Google Drive folder? Its URL is
https://drive.google.com/open?id=0B6MjdCeX8_OvVUpaZTNIem96LXM&authuser=0

It seems that dcraw works fine in a command prompt, but when it is executed from LZ, it fails to pass its output filename to LZ.
To check if this guess is correct, I created a modified version of LZ and uploaded as "LightZone-Installer-4.1.0rc1-20150215-x86.exe" in that Google Drive folder. Would you check if it works, and post its LightZone.log again?

Masahiro

**Comment by ADAM-SJ** [comment]
Hi Masahiro

I managed to download the LightZone installer ok (I haven’t tested it yet).

I can’t figure out how to upload the output.pgm? Can you tell me how to do it please?

Adam

**Comment by ktgw0316** [comment]
If you have a google account you can login and upload files, but if it didn't work, please send the file to my mail address: arctica0316@gmail.com

**Comment by ADAM-SJ** [comment]
Hi Masahiro

non of the email accounts I have will let you send attachment above 25MB. I opened a gmail account and uploaded the output.pgm file to google drive and shared it with your email
 arctica0316@gmail.com

Hope you can see it
Adam

**Comment by ADAM-SJ** [comment]
Hi Masahiro

Good news LightZone-Installer-4.1.0rc1-20150215-x86.exe works. RAW files (Canon, Panasonic, Nikon) can now be both browsed and EDITED. I have attached the log file.

Only thing that seems strange is that the PANASONIC GX7 RAW thumbnails / browse/edit etc. look really terrible in terms of noise. All the files came from Imaging Resource and are of comparable quality?

Anyway good news and a big step forward.
Thanks for your help and patience
Adam

**Comment by ktgw0316** [comment]
Hi Adam,
I'm glad to hear that the 4.1.0rc1-20150215-x86 works fine. I also checked the output.pgm and confirmed that it decoded correctly. :+1: 

As for GX7, could you create another output.pgm from a GX7 raw file and upload it again? I'll look into it and compare it to one from my Windows machine.

**Comment by ADAM-SJ** [comment]
Hi there Masahiro

sorry for the delay I am very busy as we have family visiting.

Haven’t had time to create another output.pgm for the GX7 raw file. However the GX7 thumbnail and the browse of the GX7 have funny colours and lots of noise. When you go into edit it looks as you would expect it to look (if you remember it is one of the test images from Imaging Resource for the GX7). It looks to me as if the RAW Tone Curve for the GX7 is being applied to the EDIT image but not to the thumbnail or the browse image.

Hope this helps, can do more when I have a bit more time.

Adam
