### ISSUE TITLE
Recommendations for the LightZone project

### ISSUE THREAD

**Issue by samrocketman** [ktgw0316/LightZone#168]
I think it would be better for this project to consolidate under one banner for where collaboration happens.

For example, on [the lightzone project website](http://lightzoneproject.org/) there's separate links leading to different GitHub profiles for the source code and issues.
- [Source code link](https://github.com/ktgw0316/LightZone)
- [Issues link](https://github.com/Aries85/LightZone/issues)

Why?  It just so happens that at the moment the tip of each project source code is the same.  Agree on one place for all the things.  Even better, create an organization such as `https://github.com/LightZoneProject` and rally under that banner.  @Aries85 can transfer their project since all of the issues exist here.

Consider joining [The Libre Graphics Meeting](http://libregraphicsmeeting.org/2016/).  It's an annual event where creators and collaborators on open source graphics programs come together, discuss, learn, and create compatibility across different FLOSS graphics programs.

**Comment by ktgw0316** [comment]
Closed with #268.
