### ISSUE TITLE
LightZone-Installer-4.1.9-20181223-64bit.exe 

### ISSUE THREAD

**Issue by vfomino** [ktgw0316/LightZone#241]
Hi,
I have installed today LightZone-Installer-4.1.9-20181223-64bit.exe and after launching the application, almost nothing happens. 
Almost, because it shows in Task Manager and this is all !
Windows 10 Professional (x64) Version 1809 (build 17763.379)
What can I do?
Thanks.

**Comment by juhavlintula** [comment]
Do you have God Mode enabled? Check [this thread](http://lightzoneproject.org/comment/9007#comment-9007) in Lightzone forum.

**Comment by vfomino** [comment]
Yes, I had.
Deleted it and now, LightZone works.
What is the connection between these two things anyway?
Thank you.

**Comment by juhavlintula** [comment]
There is something with the Java file chooser that crashes with God Mode folder.

**Comment by REMC19** [comment]
Hi vfomino can this issue now be closed?

**Comment by vfomino** [comment]
ok

Victor Fomino
***@***.***

**Comment by REMC19** [comment]
Masahiro can you mark this as closed please.
Victor - thanks for the quick reply, are you still using LightZone if so it, are you aware that LightZone now has a presence at https://discuss.pixls.us/ (a subforum for LightZone has recently been added).

**Comment by ktgw0316** [comment]
@REMC19 @vfomino Thank you!
