### ISSUE TITLE
Web site page rendering is bad. unable to log in

### ISSUE THREAD

**Issue by andrewk8** [ktgw0316/LightZone#260]
I know this is not about the software, but not sure where else to share it.  I get this on multiple computers with different browsers (Chrome, Edge, Firefox).  Windows 10.

The web site page rendering is borderline unusable.

You can't log in to the web site.  HTTP Error 500

work around: request a password reset.

After following the e-mail link for the password reset, you can't save the password.  HTTP Error 500.  If you hit the Back button, you're at least logged in to the web site.

See video demonstration.

[Web Site Video.zip](https://github.com/Aries85/LightZone/files/7739430/Web.Site.Video.zip)

**Comment by sattvakarma** [comment]
Ditto. 

And this is not new. I have been facing this problem for over 2 years.

Today the LZ website is not opening at all. Some maintenance page from BlueHost shows up.

Updates from the LZ team/maintainers will be appreciated.

**Comment by sfink16** [comment]
I spoke to Tex, from LZ team and he told me that he's working on the problem.  He's trying to find time between his job and this.

**Comment by sattvakarma** [comment]
Thanks for the update sfink16. Appreciate it!

**Comment by sattvakarma** [comment]
any updates on the LZ website and the team members??

**Comment by REMC19** [comment]
Andrewk8, given my reply to your post of Jul 15, 2022 regarding the LightZone website is it OK to ask for this issue to now be marked as closed?

**Comment by REMC19** [comment]
Hi Masahiro - I also believe that you can now close this one.
