### ISSUE TITLE
www.lightzoneproject.org web site has been offline for several months - what's the public-facing version of the project

### ISSUE THREAD

**Issue by andrewk8** [ktgw0316/LightZone#266]
If you visit [www.lightzoneproject.org](http://www.lightzoneproject.org/)), you get a generic web page from bluehost.  The lightzone pages are gone.  It's been like this since March or April 2022.

**Comment by sattvakarma** [comment]
what is the present update on the LZ website and the team members??

**Comment by sfink16** [comment]
Most everything is redacted when I did a Whois.  Below is the partial data.  I did a traceroute as well, which points back to parking.Bluehost.com
Domain Name: lightzoneproject.org
Registry Domain ID: 0ebb8ad9c8b7483caf50a017c6ed9dc0-LROR
Registrar WHOIS Server: http://whois.godaddy.com
Registrar URL: http://www.whois.godaddy.com
Updated Date: 2022-09-13T00:21:23Z
Creation Date: 2012-12-16T12:39:59Z
Registry Expiry Date: 2022-12-16T12:39:59Z
Registrar: GoDaddy.com, LLC
Registrar IANA ID: 146
Registrar Abuse Contact Email: abuse@godaddy.com
Registrar Abuse Contact Phone: +1.4806242505

**Comment by REMC19** [comment]
With regards to lightzone.org website, I don't know if that will ever be coming back up or not. Several people have attempted to contact the person that was in control of it, but for the last few months this appears to have been to no avail.
However all is not lost.
Firstly the developer Masahiro has activated the option to post issues - and there is also the option to hold discussions at GitHub as well.
Secondly, he has also registered with the site https://pixls.us/ it is now possible to go to their Forum https://discuss.pixls.us/ and post comments and queries about LightZone there.
They have even kindly added a subforum for LightZone, but if you filter by it you won't find much just yet as it has only been done recently (if you do a normal search you will find earlier posts).
Given the above information could andrewk8 and sattvakarma please say if they consider it enough for the issue's status to be changed to closed.
Thanks.

**Comment by andrewk8** [comment]
pixls.us is a great alternative.  works for me.

**Comment by REMC19** [comment]
Hi Masahiro - I think you can now close this one as well.

**Comment by sattvakarma** [comment]
i am glad to hear that Masahiro from the LZ team is still responding to queries and also working on the LZ project.

i will go ahead and sign up on the pixls.us forum.

thank you for the updates!
