### ISSUE TITLE
ktgw0316 vs. Aries85 is confusing

### ISSUE THREAD

**Issue by andrewk8** [ktgw0316/LightZone#268]
Why is the code (ktgw0316) and issue tracker (Aries85) in separate repositories?  Besides not being clean, this is confusing.  And not helpful to new users, considering that lightzoneproject.org has been down for a long time.

bug: two different repositories

proposed solution: merge the two repositories

**Comment by sfink16** [comment]
I believe that Aries includes the legacy from the original owners of Lightzombie, which became Lightzone.  It's forked from Lightzombie.  There's actually another Lightzone related Github called AntonKast (original coder?). None of the original coders appear to be active at this time, including Doug Pardee, who had a wealth of information on the project.  I'll provide some links that I'm aware from historical documents:

https://github.com/Aries85/LightZombie
https://github.com/AntonKast/LightZone
https://github.com/Doug-Pardee (both Lightzombie and Lightzone)

**Comment by SpruceCloud** [comment]
Hello all,
    @sfink16 is correct. Project on Aries85 is a legacy - it was the first project to get a build running (on Windows) and as other people made LightZone build on other platforms in their repositories, I merged the changes back.
    
Then I had some health issues that made me stop contributing to the project. They were resolved, but at that time, my focus shifted away from photography.

@ktgw0316 I can perform a repository transfer to your account. https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository According to the documentation, it should move all the issues as well as the code.

There is potentially problem with naming - if there would be a conflict, it might be necessary to rename the currently active repository to something else, then transfer this one to a new account and then pushing the code changes to the moved repository.

**Comment by ktgw0316** [comment]
@Aries85 It is great to hear that your health issuses were resolved.

Thank you for offering the repository transfer. That is a nice idea.

I'm on a trip until January 2nd, so after that day I will prepare announcement for renaming/transfer on my current repository.

**Comment by ktgw0316** [comment]
@Aries85 I've just posted the announcement on ktgw0316#37. Would you perform the repository transfer?

**Comment by SpruceCloud** [comment]
@ktgw0316 Tried to perform the transfer, however GitHub complains that ktgw0316/LightZone exists.Tried in browser and indeed it does exist https://github.com/ktgw0316/LightZone

Can you please rename the repository?

**Comment by ktgw0316** [comment]
@Aries85 Sorry about that. I renamed it to ktgw0316/LightZone-backup. Would you try again?

**Comment by SpruceCloud** [comment]
The repository is renamed now and on different URL.

However, now the transfer fails with message `ktgw0316 already has a repository in the AntonKast/LightZone network` 

Trying to figure it out.

**Comment by SpruceCloud** [comment]
If I get it correctly, the target account should not have fork from the same source as transferred repository according to https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository :

    The target account must not have a repository with the same name, or a fork in the same network.

**Comment by ktgw0316** [comment]
@Aries85 Thank you for figuring it out. I'll ask github support to detach the forks.

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

**Comment by ktgw0316** [comment]
@Aries85 Now ktgw0316/LightZone-backup is detached from AntonKast/LightZone.

**Comment by SpruceCloud** [comment]
@ktgw0316 After filling in the details for the transfer, there is now a message that transfer has been successfully requested. :)

I hope it will be processed soon.

**Comment by ktgw0316** [comment]
@Aries85 Thank you very much!

**Comment by andrewk8** [comment]
Thanks!!!!
