### ISSUE TITLE
Missing Backup Github

### ISSUE THREAD

**Issue by sfink16** [ktgw0316/LightZone#269]
@ktgw0316 

After the merging, we are missing some of the backed up items found earlier.  Hopefully you still have the backup.

There was a discussion tabs that is missing.  The Wiki had several versions that are all missing.  It appears that the issues are missing from the backup as well.  I had one in particular on the Tone Mapper style/tool where I included screenshots.

Steve

**Comment by ktgw0316** [comment]
@sfink16 The backup repository is here: [https://github.com/ktgw0316/LightZone-backup/issues](https://github.com/ktgw0316/LightZone-backup/issues)

I'm going to copy & paste the contents as soon as possible.

**Comment by ktgw0316** [comment]
I've just transferred the [discussions](https://github.com/ktgw0316/LightZone/discussions), [open issues](https://github.com/ktgw0316/LightZone/issues?q=is%3Aopen+is%3Aissue), and the latest two [releases](https://github.com/ktgw0316/LightZone/releases) to the new repository.

**Comment by sfink16** [comment]
Thank you!
