### ISSUE TITLE
Dead link in resources

### ISSUE THREAD

**Issue by REMC19** [ktgw0316/LightZone#271]
Depending upon how confident / or not you are about the LightZone.org site getting back up and running again you might want to remove the link in the resources section of the LightZone page that took you to the LightZone learning centre - as currently that’s a dead link.

**Comment by sfink16** [comment]
May I suggest that perhaps you can edit how you think it should be by either creating a new page or edit the old ones list in https://github.com/ktgw0316/LightZone/wiki

**Comment by ktgw0316** [comment]
Fixed by 7bd2462.
