### ISSUE TITLE
Dependency  problem for fedora 37

### ISSUE THREAD

**Issue by gelderode** [ktgw0316/LightZone#276]
# After upgrade to Fedora 37

> INFO  

- Fedora 37 has marked "javahelp2" as  [retired/not maintained longer] -package and deleted it in upgrade.
But LightZone depends on it.  It's impossible to start LZ or to do a re-install.
So I can't use LZ anymore. What's a pitty. for this excellent application.

- Furthermore, people who intend to install  LZ will be confronted with this error.  

Greetings

**Comment by gelderode** [comment]
# UPDATE

- After a manual download from fedora.pkg.org for the javahelp2-f36 package and
-  reinstall the LZ package
everything works well.

*Without these steps an install in f37 will give error (dependencies -- can't find javahelp2)  because there is no javahelp2 package any more in the Fedora 37 release.   
An inconvenience for users who try to install LZ for the first time in f37*

**Comment by sfink16** [comment]
Perhaps you can add a known bug to the "Bug Report" listed here:

https://github.com/ktgw0316/LightZone/issues/new/choose or further here:

https://github.com/ktgw0316/LightZone/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by ktgw0316** [comment]
@gelderode I decided to provide the javahelp2 package for fedora on Open Build Service repository, so it would be available via package manager if you already [added the repo for LightZone](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone). I think that it will be automatically installed as a dependency when you will upgrade to new package (lightzone-4.2.4-170.2) uploaded to the repo today.
