### ISSUE TITLE
Dependency  problem for fedora 37

### ISSUE THREAD

**Issue by gelderode** [ktgw0316/LightZone#29]
# After upgrade to Fedora 37

> INFO  

- Fedora 37 has marked "javahelp2" as  [retired/not maintained longer] -package and deleted it in upgrade.
But LightZone depends on it.  It's impossible to start LZ or to do a re-install.
So I can't use LZ anymore. What's a pitty. for this excellent application.

- Furthermore, people who intend to install  LZ will be confronted with this error.  

Greetings

**Comment by ktgw0316** [comment]
@gelderode I decided to provide the javahelp2 package for fedora on Open Build Service repository, so it would be available via package manager if you already [added the repo for LightZone](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone). I think that it will be automatically installed as a dependency when you will upgrade to new package (lightzone-4.2.4-170.2) uploaded to the repo today.
