### ISSUE TITLE
dpkg-checkbuilddeps: error: Unmet build dependencies: libavcodec58

### ISSUE THREAD

**Issue by nanoav** [ktgw0316/LightZone#290]
**Describe the bug**
Cannot run lightzone on Ubuntu 22.10 and 23.04
Trying to build from source, but getting error
Cannot build for Ubuntu 23.04 libavcodec58
Suggestion :
From 22.10 is libavcodec59 used by the Ubuntu system
Is it anyway to fix it?

**Comment by ktgw0316** [comment]
The libavcodec is already removed from dependencies (47b1df0a3f3fdd019e27acab3f32d5dbb8cffa15), so I think you can build the latest master branch without problem.

Please follow [this section](https://github.com/ktgw0316/LightZone/blob/master/linux/BUILD-Linux.md#deb-package-debian-or-ubuntu) in build instruction, but replace `tarball/4.2.4` in the URL with `tarball/master`.
