### ISSUE TITLE
 java.lang.ClassNotFoundException: jiconfont.icons.FontAwesome

### ISSUE THREAD

**Issue by 4lphac** [ktgw0316/LightZone#295]
Hi,
I've got a fresh ubuntu budgie 23.04, installed lightzone from ppa and I get this error at startup: 

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: jiconfont/icons/FontAwesome
..
..
 Caused by: java.lang.ClassNotFoundException: jiconfont.icons.FontAwesome

All libjiconfont-* packages are installed, happens both on openjdk 17 (default) and 20, any clue?

 
Thanks!

**Comment by ktgw0316** [comment]
@4lphac Thank you for the report. This error was fixed in a new package ` lightzone - 5.0.0~beta1-0~202307090133~ubuntu23.04.1`, which I uploaded on PPA yesterday.  Please try `sudo apt update && sudo apt upgrade`.  If the error still occurs, feel free to reopen this issue.
