### ISSUE TITLE
Fedora install, Why no distribution version (Only rawhide)?

### ISSUE THREAD

**Issue by UbioZur** [ktgw0316/LightZone#306]
**Describe the bug**

So after trying to figure out why I couldn't get lightzone to install on Fedora 38 following the official steps (https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone). 
I have found that those steps actually only works on fedora rawhide and not on any other version of Fedora. While other distributions have different version available for them.

Is there amy reasons why the only supported version of fedora is rawhide? 

**Expected behavior**

Latest stable fedora install steps and rawhide install steps (as it is the case for debian, raspbian, etc...

**Additional context**

Any options to try install it on fedora 38 without having to compile it myself or install a different distribution?

**Comment by ktgw0316** [comment]
I'll add the package for Fedora 38 when LZ v5.0.0beta2 is available.

Fedora [orphaned javahelp2 package](https://www.spinics.net/lists/fedora-devel/msg297379.html), which is required by LZ. So we have to build it by ourselves and I've done it for rawhide, but I forgot to do it for Fedora 38.

**Comment by UbioZur** [comment]
Thanks for the explanation.

**Comment by luzpaz** [comment]
Is there any possibility of migrating away from javahelp2 at some point since upstream is not active ?

**Comment by UbioZur** [comment]
I would like to add that there is a [contributor flatpak version](https://github.com/ktgw0316/LightZone/issues/300#issuecomment-1729995346) (works on Fedora),
So it is a good alternative for me instead of compiling.

[Flathub](https://flathub.org/apps/io.github.ktgw0316.LightZone)

**Comment by ktgw0316** [comment]
Solved in 5.0.0beta2.

**Comment by luzpaz** [comment]
I'm confused @ktgw0316, Lightzone not available in the Fedora package repository ?  
https://packages.fedoraproject.org/search?query=lightzone
Results: `No results found!`

**Comment by sfink16** [comment]
> I'm confused @ktgw0316, Lightzone not available in the Fedora package repository ? https://packages.fedoraproject.org/search?query=lightzone Results: `No results found!`

Isn't [this the page](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone) @ktgw0316 is talking about?  I believe there are two ways to get LZ.  First through the repository I mention [here](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone), and second through Flatpack.  I believe that Flatpack is not up to date yet due to technical difficulties.

**Comment by ktgw0316** [comment]
@luzpaz @sfink16 

> Isn't [this the page](https://software.opensuse.org//download.html?project=home%3Aktgw0316%3ALightZone&package=lightzone) @ktgw0316 is talking about?

That's right. LightZone is not available in the official Fedora repository (or any official repository for other Linux distributions, AFAIK).

**Comment by luzpaz** [comment]
> That's right. LightZone is not available in the official Fedora repository (or any official repository for other Linux distributions, AFAIK).

* See #300
