### ISSUE TITLE
Support for Lumix DC-G90

### ISSUE THREAD

**Issue by OldNick** [ktgw0316/LightZone#308]
There is no support for Lumix DC-G90

It is supported in other apps (Darktable, Digikam etc.)

Adobe knows it as the G99 and it also goes under G91 and G95 - depending on where it's sold. It could be that Lightzone recognizes one of these variants, which means a line of code.

**Comment by sfink16** [comment]
Those software programs use Libraw and LZ does not yet.  It is coming soon, hopefully.  Here is a list of cameras that LZ can use, of which your camera is not listed:
https://ufraw.sourceforge.net/Cameras.html

**Comment by OldNick** [comment]
And the GX9 which came out after the G90 is supported - actually the characteristics are virtually the same so there could be a hack (telling whatever has to be told to treat the G90 as a GX9...)
Rawtherapee supports it (not brilliantly) - I think they use dcraw.

Just looked at the list and the GX9 isn't on it... but it works in Lightzone

**Comment by sfink16** [comment]
> And the GX9 which came out after the G90 is supported - actually the characteristics are virtually the same so there could be a hack (telling whatever has to be told to treat the G90 as a GX9...) Rawtherapee supports it (not brilliantly) - I think they use dcraw.
> 
> Just looked at the list and the GX9 isn't on it... but it works in Lightzone

Rawtherapee most certainly dose NOT use Dcraw, it uses Libraw.  The list of cameras that came out after Dcraw ended support in 2018 did not include any Canon R Series cameras.  Any camera that came out after June 1, 2018 is not supported by Dcraw (9.28) nor LZ.

**Comment by ktgw0316** [comment]
RawTherapee uses modified DCRaw (`rtengine/dcraw.cc`) to support newer cameras.  There is an open issue to migrate it to LibRaw or Rawspeed, but no progress for years: https://github.com/Beep6581/RawTherapee/issues/4462

As for the LightZone, I'm also working on patching dcraw_lz in `update_dcraw_lz` branch, because LibRaw sometimes causes strange color balance and I couldn't workaround it so far.  I'm sure most of the new cameras, except Canon CR3 format and Sigma X3F, can be supported with the patched dcraw_lz.

**Comment by sfink16** [comment]
> RawTherapee uses modified DCRaw (`rtengine/dcraw.cc`) to support newer cameras. There is an open issue to migrate it to LibRaw or Rawspeed, but no progress for years: [Beep6581/RawTherapee#4462](https://github.com/Beep6581/RawTherapee/issues/4462)
> 
> As for the LightZone, I'm also working on patching dcraw_lz in `update_dcraw_lz` branch, because LibRaw sometimes causes strange color balance and I couldn't workaround it so far. I'm sure most of the new cameras, except Canon CR3 format and Sigma X3F, can be supported with the patched dcraw_lz.

Now I'm more confused.  Apparently there are actually 4 choices.  Let me see if I understand this correctly.

1. the old DCraw for older cameras up to 2018.  This is how LZ 4.2.5 is working today.
2. Rawspeed, apparently used by Darktable, is that correct?  Looks like it doesn't read metadata except for WB, is that correct?  It doesn't do de-mosaic?  Or crop images to manufacturer specification?
3. Libopenraw, has support for CR3 Canon images, except for rendering and CFA decompress.  This could be helpful for [Issue 263](https://github.com/ktgw0316/LightZone/issues/263), correct?
4. DNGlab mention in [issue 263](https://github.com/ktgw0316/LightZone/issues/263).  Is this still an open?  BTW, the online [DNG to Raw convertor does work](https://www.onlineconverter.com/cr3-to-dng).
5. Modified DCraw, as per Rawtherapee.  **Rawtherapee 5.9  does not show EXIF, so you have no idea what the ISO is, for example.**  Big problem!

It seems that you've settled on Libraw, is that correct?

**Comment by ktgw0316** [comment]
@sfink16 LibRaw will be used when a camera cannot be supported by modified dcraw.  In other words, I'm going to use the modified dcraw as much as possible.

1-5 in your comment is correct, but the lack of EXIF support is not a problem, since LightZone parse metadata by itself anyway.  (For example, I've already add [CR3MetadataReader](https://github.com/ktgw0316/LightZone/blob/a7b8acc1e6ffabc5dbf4bfbdcd047a7952ecc3a1/lightcrafts/src/com/lightcrafts/image/metadata/CR3MetadataReader.java) .)

**Comment by OldNick** [comment]
@ktgw0316 Your mention of colour balance with libraw is one of the things that has me trying Lightzone. In Rawtherapee I've discovered / realized that the green is completely overcooked (over-saturated). 

Panasonic Lumix use Openexr as a colour space and this, apparently is "normalized on D50". What I discovered, trying Digikam is that requires a two step process with libraw - they give a lot of control. They offer a choice to use the camera colour space or D65 for extracting the data and then a choice of final colour space for editing.

If I set it to D65 I got the over-saturated green that I've been having problems with. If I set it to use the camera colour space and _then_ converted the data extracted to a D65 colour space - Prophoto (because it's what RT uses) - I got the proper colour balance - much as I get using Lightzone.

I don't know how many other cameras use Openexr - it seems to be favoured for medical imaging and 3D graphics. Could be, as Olympus and Panasonic have shared technology, it's a hangover from Olympus specializing in medical and scientific imaging.

**Comment by sfink16** [comment]
> @sfink16 LibRaw will be used when a camera cannot be supported by modified dcraw. In other words, I'm going to use the modified dcraw as much as possible.
> 
> 1-5 in your comment is correct, but the lack of EXIF support is not a problem, since LightZone parse metadata by itself anyway. (For example, I've already add [CR3MetadataReader](https://github.com/ktgw0316/LightZone/blob/a7b8acc1e6ffabc5dbf4bfbdcd047a7952ecc3a1/lightcrafts/src/com/lightcrafts/image/metadata/CR3MetadataReader.java) .)

@ktgw0316  Great news about the EXIF solution!  Perhaps @OldNick  response below is the solution from the green color issue?  As he suggest below, I'm not found of the Rawtherapee default (out of the box) setting for my Canon R7.  I simply change it to the neutral setting and work from there.  I'm not sure if that is what he meant but that was solution the RT default setting for my camera.

Steve

**Comment by OldNick** [comment]
~~I suppose .dng support is a libraw thing as well - I tried and it came out a pink horror !~~ using Adobe converter

If you want to stay open source there's an offshoot of Digikam - Showphoto that can export .dngs

**Comment by OldNick** [comment]
.dng s DO work! I have no idea why one didn't, but I've subsequently tried both - wine installed Adobe Digital negative Converter and Showfoto and ~~they both work well.~~ - Adobe doesn't, see below... 

If you have an absolutely new model you'll have to go with Adobe because the manufacturers only communicate with the "official" ecosystem. If it's a camera like mine, that came out pre-2018 but no one bothered with, you can probably go with open source.

It adds an extra step to your workflow, but you do get the joys of LightZone !!

For those on Linux this article [https://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles](https://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles) gives a very useful guide to setting up wine and getting Adobe

Could I suggest adding a paragraph to the Wiki suggesting using .dng's when the camera is unsupported?

**Comment by sfink16** [comment]
> If you have an absolutely new model you'll have to go with Adobe because the manufacturers only communicate with the "official" ecosystem. If it's a camera like mine, that came out pre-2018 but no one bothered with, you can probably go with open source.
> 
> It adds an extra step to your workflow, but you do get the joys of LightZone !!
> 
> For those on Linux this article [https://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles](url) gives a very useful guide to setting up wine and getting Adobe
> 
> Could I suggest adding a paragraph to the Wiki suggesting using .dng's when the camera is unsupported?

Clicking on your link doesn't, instead you have to copy/paste into a new tab to get it to work.

That said, [THIS LINK](https://www.onlineconverter.com/image) does work for new cameras, as it works for my R7.  I've had problems using Wine on my past Linux systems (Ubuntu primarily).  I simply selected the CR3 Convertor link and everything works fine.  I can convert an R7 CR3 Raw image to a JPG, DNG, or TIFF with no problem.  Many other conversion possibility with this online tool.

**Comment by OldNick** [comment]
@sfink16 Works now !! 

Not very good with markdown...

**Comment by OldNick** [comment]
It's a pity that one can't delete posts because I have made a mess of this thread...

There is a problem with the Adobe .dng's - I thought it was only one weird one, which can happen, but I coverted a whole folder and it came out magenta in LZ - here's the histogram :
![Histo-dng-Adobe](https://github.com/ktgw0316/LightZone/assets/2072231/229ee67f-8684-4e94-afe3-ea78f152ce18)

Showfoto .dng's, _do,_ however, work - a Showfoto .dng for the same image as above, but no magenta fog.
![Histo-dng-showfoto](https://github.com/ktgw0316/LightZone/assets/2072231/340329c6-a576-4d7d-9cf8-61273f791020)

I have no idea what is happening - I tried changing the option in adobe that changes the compatibility with different versions of adobe products - but always the same result. The Adobe ones work in Rawtherapee and other image editors, so it is an LZ peculiarity.

**Comment by sfink16** [comment]
> I have no idea what is happening - I tried changing the option in adobe that changes the compatibility with different versions of adobe products - but always the same result. The Adobe ones work in Rawtherapee and other image editors, so it is an LZ peculiarity.

@OldNick  I concur that the D65 is the problem and I think that I see where LZ has the issue, see [HERE](https://github.com/ktgw0316/LightZone/pull/305#discussion_r1323860737).

**Comment by OldNick** [comment]
@sfink16 I've been doing a bit of research - I don't understand very much of it. Openexr is favoured by the movie industry and it plays a role in HDR images. From what I gather it uses floating point calculations and allows "impossible numbers", in other words, no clipping.
But I've probably got the wrong end of the stick!

What put me onto the D50 > D65 thing is a discussion DuckDuckGo took me to between members of the Krita team - which I now can't find much to my frustration. They have their own, in house, .icc creator called Elle Stone whose site is at [https://ninedegreesbelow.com/](https://ninedegreesbelow.com/). I have to say that of all the different open source programs, Krita does the best opening raw files from a colour point of view (but they don't have the tools needed for photography - it's not their job).

Might I suggest approaching the Krita people to find out their thinking? They do take colour management very seriously.

As a general thought, I wonder, with all the developments with cameras (Vlog for instance - I haven't even tried to understand that!), the open source community isn't faced with having to completely rewrite the decoding process - as far as I understand it even libraw is patching and extending dcraw, maybe it will need rethinking from the bottom up. Which is huge.

PS - Looked at your link, looks like you're making good progress!

**Comment by sfink16** [comment]
@OldNick You have a lot of good information there!  Let's wait for the Beta2 version to come out, which I'm hoping is very soon.

**Comment by ktgw0316** [comment]
Solved in 5.0.0beta2.
