### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by hfiguiere** [ktgw0316/LightZone#311]
**Is your feature request related to a problem? Please describe.**
Linux installation made easier: Flatpak

This is not a request to do, it's just a FYI I'm doing it.
Submission to flathub
https://github.com/flathub/flathub/pull/4525

If any upstream maintainer want update permission there, just ask.

**Describe the solution you'd like**
A couple of patches are needed for Flatpak.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by hfiguiere** [comment]
Issue #303 isn't a problem either (ie it was addressed)

**Comment by hfiguiere** [comment]
Just FYI before anyone ask, it's still in the submission stage.

I'll update here when it's available.

**Comment by hfiguiere** [comment]
It's now available https://flathub.org/apps/io.github.ktgw0316.LightZone

**Comment by sfink16** [comment]
> It's now available https://flathub.org/apps/io.github.ktgw0316.LightZone

@hfiguiere This Lightzone package does not show external (USB) drive being available in the folder panel.
