### ISSUE TITLE
Unable to edit RAW files for the Fuji X10

### ISSUE THREAD

**Issue by howardlshippin** [ktgw0316/LightZone#316]
**Describe the bug**
In 5.0 Beta 1 I am unable to edit RAW files from my Fuji X10 camera.  It is possible to view them, but when I click the edit button, it tells me:  Unrecognized Image Format,  Unsupported Camera.  Version 4.2.5 edits these files without issue. 

**To Reproduce**
Open folder with RAW (.RAF) files.

**Expected behavior**
The program will edit the file.

**Screenshots**
![Screenshot_20230925_231731](https://github.com/ktgw0316/LightZone/assets/105754379/cde709a2-40a5-4b41-bbec-fefff8554d4a)

**Desktop (please complete the following information):**
 - 5.0 beta 1
 - OS: MX Linux (Debian 11)

**Comment by sfink16** [comment]
It will be fix in beta2, see it [HERE](https://github.com/ktgw0316/LightZone/issues/298#issuecomment-1649974165).

**Comment by howardlshippin** [comment]
Thank you so much! It is working fine.


--
Howard Shippin
