### ISSUE TITLE
LightZone 5.0.0.beta2 not opening under Slackware 15.0 

### ISSUE THREAD

**Issue by sattvakarma** [ktgw0316/LightZone#330]
Hello,

I am unable to open LZ 5.0.0.beta2 under Slackware 15.0.

``Starting LightZone version 5.0.0 beta2 ...
with options :
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9)
OpenJDK 64-Bit Server VM (build 11.0.21+9, mixed mode)
/usr/share/java/lightzone/*:/usr/share/java/*
Error: LinkageError occurred while loading main class com.lightcrafts.platform.linux.LinuxLauncher
        java.lang.UnsupportedClassVersionError: com/lightcrafts/platform/linux/LinuxLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
``

Any tips to get it running?

Kind regards,
Sattva

**Comment by ktgw0316** [comment]
@sattvakarma Your Java Runtime version is 11, but LZ requires version 17 or above.  Please upgrade to openjdk17 and try again.

**Comment by sattvakarma** [comment]
@ktgw0316 

thank you for the suggestion. will work on that front!

**Comment by ktgw0316** [comment]
@sattvakarma May I close this issue now?

**Comment by sattvakarma** [comment]
@ktgw0316 

yes please. 

though, i still am yet to compile the latest openjdk for use under Slackware!
