### ISSUE TITLE
PPA doesn't support Ubuntu 24.04 / Mint 22

### ISSUE THREAD

**Issue by becker44a** [ktgw0316/LightZone#342]
**Describe the bug**
PPA does not include support for Ubuntu Noble Numbat / LTS 24.04, or Mint 22 (based on 24.04)

**To Reproduce**
In Mint 22 or Ubuntu 24.04, execute:
sudo add-apt-repository  ppa:lightzone-team/lightzone

Resulting Error message:
Cannot add PPA: ''This PPA does not support noble''.

100% reproducible.

Admittedly, Ubuntu was only released on 2024-04-25, Mint 22 on Jul 25, 2024 (3 months later).  but there shouldn't be any insurmountable issue to building a release package for Ubuntu 24.04, which is the package base for numerous other distributions.

**Comment by sfink16** [comment]
I'm running 24.04 Ubuntu also but never changed my Lightzone version 23.10 (Mantic) and it works fine.  Try going into Synaptic Package manager, into the repositories, edit Lightzone, change noble to mantic.  I agree, 24.04 has not been updated in LZ but you can still call the older 23.10 to get it to work.

**Comment by becker44a** [comment]
@sfink16 
Thanks for the workaround.  I don't really need it at the moment, as am just testing Mint 22 in a VM, but have an installer script that does semi-automated post-install setup and config, would like to make it work for Mint 22 as well.  Maybe this will be fixed by the time it matters for me . . .

**Comment by becker44a** [comment]
Support for Ubuntu Noble now added.  Lightzone pkg not available yet but appears being worked on.

**Comment by ktgw0316** [comment]
@becker44a The PPA build succeeded at last, so it will be available soon.  Sorry for the delay.

**Comment by becker44a** [comment]
Thanks for the notice.  I'll be testing this soon.
